OPENAI_API_KEY = "SUA-CHAVE-DA-API-DA-OPENAI"
ZOTERO_API_KEY = "SUA-CHAVE-DA-API-DO-ZOTERO"
ZOTERO_USER_ID = "SEU-USER-ID-DO-ZOTERO"
ZOTERO_COLLECTION_KEY = "SUA-CHAVE-DA-COLECAO-DO-ZOTERO"

[connections.questoes_db]
url = "sqlite:///questoes.db"